### ISSUE TITLE
Use loops to install packages

### ISSUE THREAD

**Issue by badmutex** [cloudmesh/ansible#1]
Instead of 

``` yaml
- name: install foo
  apt: pkg=foo [etc]
- name: install bar
  apt: pkg=bar [etc]
```

repeated many times, use [loops](https://docs.ansible.com/ansible/playbooks_loops.html).
This is a lot easier to read and maintain.
